// <auto-generated />
namespace DHMRice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _25112017mig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_25112017mig));
        
        string IMigrationMetadata.Id
        {
            get { return "201711242304354_25-11-2017 mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
