// <auto-generated />
namespace DHMRice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MonthlyperBagmarketpricechanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MonthlyperBagmarketpricechanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201803080956311_Monthly perBag market price changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
