// <auto-generated />
namespace DHMRice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class chagesinrawricetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chagesinrawricetable));
        
        string IMigrationMetadata.Id
        {
            get { return "201804030910387_chages in raw rice table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
